// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2
// source: F1CarTelemetryReport.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface F1CarTelemeteryReport {
  query: string;
  pageNumber: number;
  resultsPerPage: number;
}

function createBaseF1CarTelemeteryReport(): F1CarTelemeteryReport {
  return { query: "", pageNumber: 0, resultsPerPage: 0 };
}

export const F1CarTelemeteryReport: MessageFns<F1CarTelemeteryReport> = {
  encode(message: F1CarTelemeteryReport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.pageNumber !== 0) {
      writer.uint32(16).int32(message.pageNumber);
    }
    if (message.resultsPerPage !== 0) {
      writer.uint32(24).int32(message.resultsPerPage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): F1CarTelemeteryReport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseF1CarTelemeteryReport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageNumber = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.resultsPerPage = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): F1CarTelemeteryReport {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      pageNumber: isSet(object.pageNumber) ? globalThis.Number(object.pageNumber) : 0,
      resultsPerPage: isSet(object.resultsPerPage) ? globalThis.Number(object.resultsPerPage) : 0,
    };
  },

  toJSON(message: F1CarTelemeteryReport): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.pageNumber !== 0) {
      obj.pageNumber = Math.round(message.pageNumber);
    }
    if (message.resultsPerPage !== 0) {
      obj.resultsPerPage = Math.round(message.resultsPerPage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<F1CarTelemeteryReport>, I>>(base?: I): F1CarTelemeteryReport {
    return F1CarTelemeteryReport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<F1CarTelemeteryReport>, I>>(object: I): F1CarTelemeteryReport {
    const message = createBaseF1CarTelemeteryReport();
    message.query = object.query ?? "";
    message.pageNumber = object.pageNumber ?? 0;
    message.resultsPerPage = object.resultsPerPage ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
