services:
  kafka:
    image: bitnami/kafka:3.5.2
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9094:9094

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 8189:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  f1-car-data-stub:
    image: f1-car-data-stub:dev
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_ADDRESS: kafka:9092
  
  kafka-websocket-bridge:
    image: kafka-websocket-bridge:dev
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 8765:8765
    environment:
      KAFKA_ADDRESS: kafka:9092
      WEBSOCKET_HOST: 0.0.0.0

  f1-race-viewer:
    image: f1-race-viewer:dev
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 80:80
